development:
  adapter: postgresql
  encoding: utf8
  database: homework_management_development
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  database: homework_management_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: homework_management
  pool: 5